version: '2'

services:
  https:
    build: .
    image: mperezi/apache2-ssl
    hostname: mperezi.com
    ports:
      - '80:80'
      - '443:443'
    environment:
      LETS_ENCRYPT_EMAIL: "mperezibars@gmail.com"
    volumes:
      - '$PWD/html:/usr/local/apache2/htdocs'
      - '$PWD/conf/extra:/usr/local/apache2/conf/extra'
      - 'certs:/etc/letsencrypt'

volumes:
  certs:
