version: '2'

services:
  web:
    build: .
    image: mperezi/apache2-letsencrypt
    restart: always
    hostname: mperezi.com
    ports:
      - '80:80'
      - '443:443'
    environment:
      LETS_ENCRYPT_EMAIL: "mperezibars@gmail.com"
    volumes:
      - '$PWD/html:/var/www/html'
      - '$PWD/conf/sites-available:/etc/apache2/sites-available'
      - 'certs:/etc/letsencrypt'

volumes:
  certs:
